<a href="https://colab.research.google.com/github/ejjjjkang/computational_methods/blob/main/Clustering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip -V

pip 23.0.1 from /Users/eunkang/PycharmProjects/comproject/comproject/lib/python3.9/site-packages/pip (python 3.9)
Note: you may need to restart the kernel to use updated packages.


In [ ]:
!pip install youtube-comment-downloader

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 293.8/293.8 kB 1.2 MB/s eta 0:00:00a 0:00:01

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip


In [ ]:
!youtube-comment-downloader --youtubeid ahPdfGBLGBo --output output1.json

Downloaded 5401 comment(s)
[177.28 seconds] Done!


In [ ]:
import json

output = 'output1.json'

In [ ]:
tweets = []
with open(output, 'r') as file:
    for line in file:
        tweets.append(json.loads(line))

In [ ]:
tweets[0]

{'cid': 'UgztBzbf7U8dOHoGsUN4AaABAg',
 'text': '1번은 게임에서도 저렇게 안됨.',
 'time': '18 hours ago',
 'author': '@mumn',
 'channel': 'UCtXTWNRPQZTm_2yq5SObwFA',
 'votes': '1',
 'photo': 'https://yt3.ggpht.com/bRqMFZprydlgVtQ1yn43R8iFxQ15H1heI-Y7KnaYax1rscYkez_wZB-albUFSxLijgOgk_HAJg=s176-c-k-c0x00ffffff-no-rj',
 'heart': False,
 'reply': False,
 'time_parsed': 1695609291.974138}

In [ ]:
comment_array = []

for i in tweets:
    comment_array.append(i['text'])


In [ ]:
from transformers import (
    AdamW,
    MT5ForConditionalGeneration,
    T5ForConditionalGeneration,
    T5Tokenizer,
    AutoTokenizer,
    get_linear_schedule_with_warmup,
    AutoModelWithLMHead
)
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans

In [ ]:
tokenizer=AutoTokenizer.from_pretrained('T5-base')
model=AutoModelWithLMHead.from_pretrained('T5-base', return_dict=True)

/Users/eunkang/PycharmProjects/comproject/comproject/lib/python3.9/site-packages/transformers/models/auto/modeling_auto.py:1479: FutureWarning: The class `AutoModelWithLMHead` is deprecated and will be removed in a future version. Please use `AutoModelForCausalLM` for causal language models, `AutoModelForMaskedLM` for masked language models and `AutoModelForSeq2SeqLM` for encoder-decoder models.
  warnings.warn(


In [ ]:
tf_idf_vectorizor = TfidfVectorizer(max_features = 20000) #1
tf_idf = tf_idf_vectorizor.fit_transform(comment_array) #2
tf_idf_array = tf_idf.toarray() #3
pd.DataFrame(tf_idf_array, columns=tf_idf_vectorizor.get_feature_names_out()).head() #4

00  000   01   02   03  0335   04   05   06   07  ...  힘내줍시다  힘든와중에  힘들거라  \
0  0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   0.0   
1  0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   0.0   
2  0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   0.0   
3  0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   0.0   
4  0.0  0.0  0.0  0.0  0.0   0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   0.0   

   힘들다  힘들수도  힘들어서  힘들어요  힘들지  힘부르크  힝민쏜  
0  0.0   0.0   0.0   0.0  0.0   0.0  0.0  
1  0.0   0.0   0.0   0.0  0.0   0.0  0.0  
2  0.0   0.0   0.0   0.0  0.0   0.0  0.0  
3  0.0   0.0   0.0   0.0  0.0   0.0  0.0  
4  0.0   0.0   0.0   0.0  0.0   0.0  0.0  

[5 rows x 10298 columns]

In [ ]:
kmeans = KMeans(n_clusters=5, algorithm = 'auto')

In [ ]:
kmeans.fit(tf_idf_array)

/Users/eunkang/PycharmProjects/comproject/comproject/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
/Users/eunkang/PycharmProjects/comproject/comproject/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:1420: FutureWarning: algorithm='auto' is deprecated, it will be removed in 1.3. Using 'lloyd' instead.
  warnings.warn(


KMeans(algorithm='auto', n_clusters=5)

In [ ]:
total_array=np.array([tokenizer.encode_plus(comment_array[0],
                      add_special_tokens=True,max_length=30,
   pad_to_max_length=True,return_attention_mask=True)['input_ids']])

for i in comment_array[1:]:
    new_array=np.array([tokenizer.encode_plus(i,
                        add_special_tokens=True, #3
                        max_length=30,
                        pad_to_max_length=True,
                        return_attention_mask=True)['input_ids']])
    total_array = np.append(total_array,new_array,axis=0)
print(total_array)

[[  209     2     3 ...     0     0     0]
 [    3     2     3 ...     0     0     0]
 [  216   243    24 ...     0     0     0]
 ...
 [ 3320    26    32 ...     0     0     0]
 [ 3885 21979  1737 ...     0     0     0]
 [    3     2     1 ...     0     0     0]]


In [ ]:
comment_array[0]

'1번은 게임에서도 저렇게 안됨.'

In [ ]:
cluster_assignment = kmeans.labels_
clustered_sentences = [[] for i in range(5)]
for sentence_id, cluster_id in enumerate(cluster_assignment):
    clustered_sentences[cluster_id].append(comment_array[sentence_id])
for i, cluster in enumerate(clustered_sentences):
    print("Cluster ", i+1)
    print(cluster)
    print("")

Cluster  1
['He said that his favourite was against Nowrich in May 2022', "He's still fast but he was almost 36km/h in the 18/19. At that time he was perfect in every way.  People say the 21/22 season is the best but not me.", 'amazing talent being watednij tottenham, he needs to leave and go to a top club', 'he  is  epl legend .', 'Heung Min is just a great player and such a good person', 'When he realized that he was alone and no one was running along with him, he decided to use his pace. Great player♥️🪄', 'I wish that he played for Real Madrid', "He's soooo fast!!!", 'from the way he celebrates his best goals you can say how humble of a person he is.', "I'm so proud of him , he is alone making his team win 😭😭 last goal is unbelievable 😵\u200d💫😵", 'Bro said bye he just did not stop runing in one', 'So spurs fans is he your top 5 all time player for the club?', 'he is the next mbappe and hes so underatted', "He's just too fast.", 'He makes us koreans proud to the moon and back', 'He i

In [ ]:
import requests

In [ ]:
API_URL = "https://api-inference.huggingface.co/models/Voicelab/vlt5-base-keywords"
headers = {"Authorization": "Bearer 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"}

def query(payload):
    response = requests.post(API_URL, headers=headers, json=payload)
    return response.json()

for i, cluster in enumerate(clustered_sentences):
    output = query({"inputs": str(cluster),  "wait_for_model": True})
    print(output)

{'error': 'Service Unavailable'}
{'error': 'Service Unavailable'}
[{'generated_text': 'amazing sonny, world class, world class, '}]
{'error': 'Service Unavailable'}
{'error': 'Service Unavailable'}
